/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kcdqoghbsiwwwsltdwqn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjZHFvZ2hic2l3d3dzbHRkd3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5Mzg2ODEsImV4cCI6MjA4NTUxNDY4MX0.xAfq-yyBnx4VM4gG53NcMMtUe7vUFX-LSDXibw6aVXk"